const kkSongs = ["Agent K.K.",
    "Aloha K.K.",
    "Café K.K.",
    "Comrade K.K.",
    "DJ K.K.",
    "Forest Life",
    "Go K.K. Rider",
    "I Love You",
    "Imperial K.K.",
    "K.K. Aria",
    "K.K. Ballad",
    "K.K. Blues",
    "K.K. Bossa",
    "K.K. Calypso",
    "K.K. Casbah",
    "K.K. Chorale",
    "K.K. Condor",
    "K.K. Country",
    "K.K. Cruisin'",
    "K.K. D&B",
    "K.K. Dirge",
    "K.K. Dixie",
    "K.K. Étude",
    "K.K. Faire",
    "K.K. Folk",
    "K.K. Fusion",
    "K.K. Gumbo",
    "K.K. House",
    "K.K. Jazz",
    "K.K. Lament",
    "K.K. Love Song",
    "K.K. Lullaby",
    "K.K. Mambo",
    "K.K. Marathon",
    "K.K. March",
    "K.K. Metal",
    "K.K. Parade",
    "K.K. Ragtime",
    "K.K. Rally",
    "K.K. Reggae",
    "K.K. Rock",
    "K.K. Rockabilly",
    "K.K. Safari",
    "K.K. Salsa",
    "K.K. Samba",
    "K.K. Ska",
    "K.K. Sonata",
    "K.K. Song",
    "K.K. Soul",
    "K.K. Steppe",
    "K.K. Swing",
    "K.K. Tango",
    "K.K. Technopop",
    "K.K. Waltz",
    "K.K. Western",
    "King K.K.",
    "Lucky K.K.",
    "Marine Song 2001",
    "Mountain Song",
    "Mr. K.K.",
    "My Place",
    "Neapolitan",
    "Only Me",
    "Pondering",
    "Rockin' K.K.",
    "Señor K.K.",
    "Soulful K.K.",
    "Spring Blossoms",
    "Stale Cupcakes",
    "Steep Hill",
    "Surfin' K.K.",
    "The K. Funk",
    "To the Edge",
    "Two Days Ago",
    "Wandering"
];